source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!


target 'ACYKit_Example' do
	
	
  pod 'ACYKit', :path => '../'

  pod 'CocoaLumberjack', :inhibit_warnings => true
  pod 'Masonry', :inhibit_warnings => true
  pod 'HexColors', '4.0.0', :inhibit_warnings => true # 5.0.0 is written in Swift 3
  pod 'SDWebImage', :inhibit_warnings => true
  pod 'MLeaksFinder', :inhibit_warnings => true
  pod 'Aspects'

  target 'ACYKit_Tests' do
    inherit! :search_paths
	
    pod 'Kiwi', :inhibit_warnings => true
#	pod 'FBSnapshotTestCase'
  end
  
end


#  pod 'FLAnimatedImage'
#  pod 'PINRemoteImage'
#  pod 'TAOverlay'

#pod 'AFNetworking", :git => 'https://github.com/gowalla/AFNetworking.git', :branch => 'dev'
#pod 'AFNetworking', :git => 'https://github.com/gowalla/AFNetworking.git', :commit => '082f8319af'
