platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!



target 'ACYKit_Example' do
  pod 'ACYKit', :path => '../'

  pod 'CocoaLumberjack'
  pod 'Masonry'
  pod 'HexColors', '4.0.0' # 5.0.0 is written in Swift 3
  pod 'SDWebImage'
  pod 'MLeaksFinder'

  target 'ACYKit_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
#	pod 'FBSnapshotTestCase'
  end
end


#  pod 'FLAnimatedImage'
#  pod 'PINRemoteImage'
#  pod 'TAOverlay'
