# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.3
language: objective-c
rvm: 2.4.1
cache: 
    - bundler
    - cocoapods
podfile: Example/Podfile
before_install:
    - bundle
    - bundle exec pod install --project-directory=Example
script:
    - cd Example
    - bundle exec fastlane test
    - cd ..
    - pod lib lint
