# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

rvm: 2.4
osx_image: xcode8.3
language: objective-c
cache: 
    - bundler
    - cocoapods
podfile: Example/Podfile
install:
    - bundle install --without=documentation
    - bundle exec pod install --project-directory=Example
script:
    - cd Example
    - bundle exec fastlane test_in_travis
    - cd ..
    - pod lib lint --quick
after_success: 
    - bash <(curl -s https://codecov.io/bash) -f ./Example/fastlane/test_output/code_coverage/cobertura.xml

