# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

rvm: 2.4
osx_image: xcode8.3
language: objective-c
cache: 
    - bundler
    - cocoapods
podfile: Podfile
install:
    - bundle install --without=documentation
    - bundle exec pod install
script:
    - bundle exec fastlane test_in_travis
    - pod lib lint --allow-warnings
after_success: 
    - bash <(curl -s https://codecov.io/bash) -f ./fastlane/test_output/code_coverage/cobertura.xml



