#!/usr/local/bin/ruby
SCHEME      = "ACYKit"
XCWORKSPACE = "#{SCHEME}.xcworkspace"
XCODEPROJ   = "#{SCHEME}.xcodeproj"

fastlane_version "2.54.0"

default_platform :ios

platform :ios do
  
############################################################
##########################  TEST  ##########################
############################################################

  desc "Runs all the tests"
  lane :test do |options|
    env_ci = options[:env_ci]
    scan(
      scheme: SCHEME,
      devices: "iPhone 7",
      code_coverage: true
    )
    code_coverage(
      env_ci: env_ci
    )
  end

############################################################
#####################  CODE COVERAGE  ######################
############################################################

  desc "Run slather to generate a code coverage report"
  lane :code_coverage do |options|
    env_ci    = options[:env_ci]
    slather(
      cobertura_xml: env_ci,
      html: !env_ci,
      show: !env_ci,
      source_files: "#{SCHEME}/#{SCHEME}/*",
      output_directory: "fastlane/test_output/code_coverage/",
      scheme: SCHEME,
      workspace: XCWORKSPACE,
      proj: XCODEPROJ,
      ignore: [
        "Pods/*"
      ]
    )
  end

############################################################
#######################  TRAVIS-CI  ########################
############################################################

  desc "Run unit tests in bitrise"
  lane :test_in_bitrise do
    test(
      env_ci: true,
    )
  end

end
